apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto:2.0
        resources:
          requests:
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8883
        volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: mosquitto-ca-cert
              mountPath: /mosquitto/config/certs/ca.crt
              subPath: ca.crt
              readOnly: true
            - name: mosquitto-server-cert
              mountPath: /mosquitto/config/certs/server.crt
              subPath: server.crt
              readOnly: true
            - name: mosquitto-server-key
              mountPath: /mosquitto/config/certs/server.key
              subPath: server.key
              readOnly: true
      volumes:
        - name: mosquitto-config
          configMap:
            name: mosquitto-certs
        - name: mosquitto-certs
          configMap:
            name: mosquitto-config
            items:
              - key: ca.crt
                path: ca.crt
        - name: mosquitto-certs
          configMap:
            name: mosquitto-certs
            items:
              - key: server.crt
                path: server.crt
        - name: mosquitto-certs
          configMap:
            name: mosquitto-certs
            items:
              - key: server.key
                path: server.key