apiVersion: v1
kind: Service
metadata:
  name: mosquitto
spec:
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
  - port: 1883
    name: "1883"
    targetPort: 1883
  - port: 8883
    name: "8883"
    targetPort: 8883